name: Keep Render Awake

on:
  schedule:
    # This runs every 15 minutes
    - cron: "*/15 * * * *"
  workflow_dispatch: # Allows manual trigger

jobs:
  ping-render:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render server
        run: |
          curl -I https://blogsite-3-zaob.onrender.com || echo "Failed to ping"
